### ISSUE TITLE
Dialog.show({...}) is not showing properly for first time

### ISSUE THREAD

**Issue by sirtok4** [CodingByJerez/react-native-alert-notification#2]
When I open the app and run Dialog.show({...}), the box doesnt show up properly. And if I open it for a second time it open with no problems.

**Comment by CodingByJerez** [comment]
@sirtok4 I don't know your exact usage but it can't be used on first render because the script needs to get the REF,

You must include Dialog.show in a callback function for example return from submit or click button

Or try with the useLayoutEffect hook

**Comment by sirtok4** [comment]
I will try it! Yea, Im using it in callbacks. It runs well but the box seems to disappear in 1 second. 

Im using expo, so I updated the dependence **react-native-safe-area-context**. I hope it works now

**Comment by CodingByJerez** [comment]
@sirtok4 I pushed a fix for you normally it's ok try with the update
