### ISSUE TITLE
Toast is shown under the modal screen.

### ISSUE THREAD

**Issue by daniel-keen** [CodingByJerez/react-native-alert-notification#22]
When using presentation: 'modal' on a screen, calling Toast.Show() shows the toast under the screen.
Is there a fix for that?

**Comment by CodingByJerez** [comment]
AlertNotificationRoot must surround your entire project

**Comment by daniel-keen** [comment]
> AlertNotificationRoot must surround your entire project

It does, yet I'm still having the issue

**Comment by CodingByJerez** [comment]
This is weird, maybe you have a problem with zindex or a native modal

**Comment by RomainLAU** [comment]
Hi @daniel-keen ! Did you find a solution to this issue ?
