### ISSUE TITLE
Root Component showing error 

### ISSUE THREAD

**Issue by mahipalsingh-syt** [CodingByJerez/react-native-alert-notification#9]
Root Component Showing Error 

```Type '{ children: Element; }' has no properties in common with type 'IntrinsicAttributes & IProps'```

**Comment by CodingByJerez** [comment]
It was pushed 👍🏼
#10

**Comment by mahipalsingh-syt** [comment]
thanks

**Comment by mahipalsingh-syt** [comment]
Getting another issue at launch Time, screen attached .
![Simulator Screen Shot - iPhone 13 - 2022-07-29 at 18 19 10](https://user-images.githubusercontent.com/64964760/181763963-4c8b9143-a025-4445-bc7b-b057b616a6d3.png)

```render() {
    return (
      <>
        <Root>
          <SafeAreaView style={styles.container}>
            <SectionList
              sections={DATA}
              keyExtractor={(_, index) => index.toString()}
              renderItem={({ item }) => <Button {...item} />}
              renderSectionHeader={({ section: { title } }) => (
                <Text style={styles.header}>{title}</Text>
              )}
            />
          </SafeAreaView>
        </Root>
      </>
    )
  }```

**Comment by mahipalsingh-syt** [comment]
but if removed Root from above code then code will start working but alert will not be visible

**Comment by mahipalsingh-syt** [comment]
@CodingByJerez

**Comment by CodingByJerez** [comment]
Strange it passed all the tests and for me it works. 
You thought about clearing the caches?

**Comment by mahipalsingh-syt** [comment]
i got problem , its  https://reactnative.dev/docs/usecolorscheme, in my project some components support class type and usecolorscheme is functional Hook that's why its crashing @CodingByJerez

**Comment by CodingByJerez** [comment]
[0.2.2](https://github.com/CodingByJerez/react-native-alert-notification/releases/tag/v0.2.2)

Normally it should work with this patch tell me.

**Comment by mahipalsingh-syt** [comment]
no, @CodingByJerez  if you replace useColorScheme with Appearance.getColorScheme() then only it work for both class and functional component

**Comment by CodingByJerez** [comment]
useColorScheme is not placed in a class, It's only because you are using an old version of react native below version 0.64
